Initiale Radar-GUI
Calanas/tech-radar pull request #26
Opened 2023-03-08 13:24 UTC by oliver-allgeier

Closes #16 
Initiale GUI auf Grundlage der Zalando-Basis. Außerdem lokale Google-Fonts, Allgeier-Farben-Sammlung und lint-Anpassungen.

2023-03-08 13:30 UTC, oliver-allgeier reviewed
Ich habe mal die License und die Readme des Flex-Fonts mit committed zur Info. Weiß nicht, ob das notwendig ist.

2023-03-08 13:42 UTC, Calanas commented
> Ich habe mal die License und die Readme des Flex-Fonts mit committed zur Info. Weiß nicht, ob das notwendig ist.

Das hängt von der Art der Lizenz ab, bei den meisten ist es so, dass der Ursprung genannt werden muss. Daher passt das schon.

2023-03-08 13:43 UTC, Calanas approved these changes

2023-03-08 14:07 UTC, oliver-allgeier commented on frontend/tsconfig.json
> +  "typeRoots": ["./src/types/"]
done

2023-03-08 14:07 UTC, oliver-allgeier commented on frontend/src/types/RadarVisualizationConfig.d.ts
> +
done

2023-03-08 15:17 UTC, Calanas requested changes

2023-03-08 15:17 UTC, Calanas commented on frontend/src/app/model/radar-visualization-config.ts
> +    name: string;
Erstelle doch bitte noch ein Quadrant Modell, weil wir das später sowieso brauchen.

2023-03-09 07:15 UTC, Calanas approved these changes

2023-03-09 07:22 UTC, merged